name: etiyatechassessment
description: A new Flutter project.

version: 1.0.3+4

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  auto_route: ^5.0.1
  cupertino_icons: ^1.0.2
  device_info_plus: ^3.2.1
  dio: ^4.0.6
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_vector_icons: ^1.0.0
  flutter_svg: ^1.0.0
  google_fonts: ^3.0.1
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  internet_connection_checker: ^0.0.1+2
  intl: ^0.17.0
  lottie: ^1.1.0
  nb_utils: ^4.4.6
  package_info_plus: ^1.0.6

dev_dependencies:

  auto_route_generator: ^5.0.1
  bloc_test: ^9.0.2
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.12.0
  integration_test:
    sdk: flutter
  mocktail: ^0.2.0



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/google_fonts/
    - assets/images/

    - assets/languages/
    - assets/animations/

    - assets/files/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
